name: iconfont_convert
description: A library to generate Flutter IconData Class from www.iconfont.cn
version: 1.0.0
homepage: https://github.com/wkan/iconfont_convert

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.1
  args: ^2.4.0
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

executables:
  iconfont_convert:
